apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.tomcatmetadata.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.tomcatmetadata.label}}

  template:
    metadata:
      name: {{.Values.tomcatmetadata.name}}
      labels:
        app: {{.Values.tomcatmetadata.label}}
    spec:
      containers:
      - name: {{.Values.tomcatmetadata.containername}}
        image: "{{.Values.image.repository}}:{{.Values.image.tag}}-{{.Values.image.jre}}"
        