apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.loadbalancer.name }}
spec:
  type: {{ .Values.service.loadbalancer.type }}
  ports:
  - port: {{ .Values.service.loadbalancer.port }}
    targetPort: {{.Values.image.spec.containerport}}
  selector:
    app: {{.Values.tomcatmetadata.label}}