replicaCount: 3

tomcatmetadata:
  name: tomcatserver
  label: front-end
  containername: frontend
  

image:
  repository: tomcat
  tag: "9.0"
  jre: jre17
  spec:
    containerport: 8080

service:
  loadbalancer:
    name: front-end
    type: LoadBalancer
    port: 80
